### ISSUE TITLE
Runtime failure running stylist

### ISSUE THREAD

**Issue by DJDavies2** [MetOffice/stylist#33]
I'm getting the following failure running stylist:

"""
Traceback (most recent call last):
  File "/home/h01/frwd/cylc-run/StylistCmake/work/1/build_stylist__rhel7/install/bin/stylist", line 33, in <module>
    sys.exit(load_entry_point('stylist===0.2-SNAPSHOT', 'console_scripts', 'stylist')())
  File "/home/h01/frwd/cylc-run/StylistCmake/work/1/build_stylist__rhel7/install/bin/stylist", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/net/project/ukmo/scitools/opt_scitools/environments/experimental/2021_03_03-2/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File "/net/project/ukmo/scitools/opt_scitools/environments/experimental/2021_03_03-2/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for stylist
"""

The command is:

/path/to/stylist/bin/stylist -style simple -configuration path/to/config.ini input.F90

having installed and configured with scitools/experimental-current.  Does anyone have any ideas as to what is happening?

**Comment by MatthewHambley** [comment]
This sort of site specific question would be much better asked of people at your site rather than to the world in general.

In this case I'm not sure what's happening there but note we have never used stylist with any of the experimental Python environments. Furthermore it looks like stylist is being built and installed every time the suite runs which is probably not the best way to do it.
